### ISSUE TITLE
Running the example gives a  Content Encoding Error

### ISSUE THREAD

**Issue by jakewilliami** [jofas/actix_proxy#18]
Example `main.rs` from #17:
```rust
use awc::Client;

use actix_web::{get, web, HttpResponse, App, HttpServer};

use actix_proxy::{IntoHttpResponse, SendRequestError};

#[get("/{url:.*}")]
async fn proxy(
    path: web::Path<(String,)>,
    client: web::Data<Client>,
) -> Result<HttpResponse, SendRequestError> {
    let (url,) = path.into_inner();

    let url = format!("https://duckduckgo.com/{url}");

    // here we use `IntoHttpResponse` to return the request to
    // duckduckgo back to the client that called this endpoint
    Ok(client.get(&url).send().await?.into_http_response())
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .app_data(web::Data::new(Client::default())) // This is the important line
            .service(proxy)
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
```

And example `Cargo.toml` adapted from #2:
```toml
[package]
name = "test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-proxy = "0.2.0"
actix-web = { version = "^4.3.0" }
awc = { version = "^3.1.0", features = ["openssl"] }
openssl = { version = "^0.10.32" }
```

However, I get a Conent Encoding Error: 

![Image](https://github.com/user-attachments/assets/bddae6a4-1c99-4671-a800-c4715327ae82)

Is there something I'm doing wrong?

I saw @Sleepful's [comment](https://github.com/jofas/actix_proxy/issues/17#issuecomment-2222184707) and [CORS Anywhere](https://github.com/Rob--W/cors-anywhere) is essentially the functionality I want to emulate, but using Actix.  You could _entertain the notion_ that my company blocked [Connections](https://www.nytimes.com/games/connections) so I was hoping to create a proxy to it on an existing website I have whose server is running on Actix.  That might bypass the hypothetical block...

P.S., thank you for your work on this package.  It looks really promising.  I have also seen [redirection.io's Actix Proxy](https://github.com/redirectionio/actix-proxy), but it does a lot of magic-y things.  I like that with this package I can still easily specify the route, for example.  It seems to meld well with base Actix.
