### ISSUE TITLE
Not working with ssl ?

### ISSUE THREAD

**Issue by chaycee** [jofas/actix_proxy#2]
Example isnt working with https request

**Comment by jofas** [comment]
Hi @chaycee,

have you imported `awc` with openssl enabled? My dependencies look like this and the example compiles:

```toml
[dependencies]
actix-web = { version = "^4.3.0" }
awc = { version = "^3.1.0", features = ["openssl"] }
openssl = { version = "^0.10.32" }
```
